//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPCajaLite.OperacionesCheques {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjetoRespuestaCajaCheque", Namespace="http://schemas.datacontract.org/2004/07/CAPOperacionesChequesService")]
    [System.SerializableAttribute()]
    public partial class ObjetoRespuestaCajaCheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AplicacionField;
        
        private bool EstatusExitoField;
        
        private CAPCajaLite.OperacionesCheques.Documento[] ListaDocumentosField;
        
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Aplicacion {
            get {
                return this.AplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicacionField, value) != true)) {
                    this.AplicacionField = value;
                    this.RaisePropertyChanged("Aplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool EstatusExito {
            get {
                return this.EstatusExitoField;
            }
            set {
                if ((this.EstatusExitoField.Equals(value) != true)) {
                    this.EstatusExitoField = value;
                    this.RaisePropertyChanged("EstatusExito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CAPCajaLite.OperacionesCheques.Documento[] ListaDocumentos {
            get {
                return this.ListaDocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDocumentosField, value) != true)) {
                    this.ListaDocumentosField = value;
                    this.RaisePropertyChanged("ListaDocumentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/CAPOperacionesChequesService")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apPatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bcoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caveTranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codSegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short digInterField;
        
        private string importeDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numCtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int plaCompField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int preMarcField;
        
        private string tipoPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apMat {
            get {
                return this.apMatField;
            }
            set {
                if ((object.ReferenceEquals(this.apMatField, value) != true)) {
                    this.apMatField = value;
                    this.RaisePropertyChanged("apMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apPat {
            get {
                return this.apPatField;
            }
            set {
                if ((object.ReferenceEquals(this.apPatField, value) != true)) {
                    this.apPatField = value;
                    this.RaisePropertyChanged("apPat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bco {
            get {
                return this.bcoField;
            }
            set {
                if ((object.ReferenceEquals(this.bcoField, value) != true)) {
                    this.bcoField = value;
                    this.RaisePropertyChanged("bco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caveTran {
            get {
                return this.caveTranField;
            }
            set {
                if ((object.ReferenceEquals(this.caveTranField, value) != true)) {
                    this.caveTranField = value;
                    this.RaisePropertyChanged("caveTran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codSeg {
            get {
                return this.codSegField;
            }
            set {
                if ((this.codSegField.Equals(value) != true)) {
                    this.codSegField = value;
                    this.RaisePropertyChanged("codSeg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short digInter {
            get {
                return this.digInterField;
            }
            set {
                if ((this.digInterField.Equals(value) != true)) {
                    this.digInterField = value;
                    this.RaisePropertyChanged("digInter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string importeDocumento {
            get {
                return this.importeDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.importeDocumentoField, value) != true)) {
                    this.importeDocumentoField = value;
                    this.RaisePropertyChanged("importeDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numCta {
            get {
                return this.numCtaField;
            }
            set {
                if ((object.ReferenceEquals(this.numCtaField, value) != true)) {
                    this.numCtaField = value;
                    this.RaisePropertyChanged("numCta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int plaComp {
            get {
                return this.plaCompField;
            }
            set {
                if ((this.plaCompField.Equals(value) != true)) {
                    this.plaCompField = value;
                    this.RaisePropertyChanged("plaComp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int preMarc {
            get {
                return this.preMarcField;
            }
            set {
                if ((this.preMarcField.Equals(value) != true)) {
                    this.preMarcField = value;
                    this.RaisePropertyChanged("preMarc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoPagoField, value) != true)) {
                    this.tipoPagoField = value;
                    this.RaisePropertyChanged("tipoPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOperacionCajaCheque", Namespace="http://schemas.datacontract.org/2004/07/CAPOperacionesChequesService")]
    [System.SerializableAttribute()]
    public partial class RespuestaOperacionCajaCheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesCheques.ICAPOperacionesCheques")]
    public interface ICAPOperacionesCheques {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAPOperacionesCheques/RespuestaOperacionesCheques", ReplyAction="http://tempuri.org/ICAPOperacionesCheques/RespuestaOperacionesChequesResponse")]
        CAPCajaLite.OperacionesCheques.RespuestaOperacionCajaCheque RespuestaOperacionesCheques(CAPCajaLite.OperacionesCheques.ObjetoRespuestaCajaCheque objetoRespuestaCheques, string IdSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAPOperacionesCheques/ConsultaOperacionesCheques", ReplyAction="http://tempuri.org/ICAPOperacionesCheques/ConsultaOperacionesChequesResponse")]
        CAPCajaLite.OperacionesCheques.ObjetoRespuestaCajaCheque ConsultaOperacionesCheques(string IdSesion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICAPOperacionesChequesChannel : CAPCajaLite.OperacionesCheques.ICAPOperacionesCheques, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAPOperacionesChequesClient : System.ServiceModel.ClientBase<CAPCajaLite.OperacionesCheques.ICAPOperacionesCheques>, CAPCajaLite.OperacionesCheques.ICAPOperacionesCheques {
        
        public CAPOperacionesChequesClient() {
        }
        
        public CAPOperacionesChequesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAPOperacionesChequesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAPOperacionesChequesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAPOperacionesChequesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPCajaLite.OperacionesCheques.RespuestaOperacionCajaCheque RespuestaOperacionesCheques(CAPCajaLite.OperacionesCheques.ObjetoRespuestaCajaCheque objetoRespuestaCheques, string IdSesion) {
            return base.Channel.RespuestaOperacionesCheques(objetoRespuestaCheques, IdSesion);
        }
        
        public CAPCajaLite.OperacionesCheques.ObjetoRespuestaCajaCheque ConsultaOperacionesCheques(string IdSesion) {
            return base.Channel.ConsultaOperacionesCheques(IdSesion);
        }
    }
}
