//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPControlCaja.CAPAfectacionCajaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjetoAfectacionCaja", Namespace="http://schemas.datacontract.org/2004/07/CAPCajaServices")]
    [System.SerializableAttribute()]
    public partial class ObjetoAfectacionCaja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConceptoField;
        
        private int DivisaField;
        
        private string EmpleadoField;
        
        private decimal ImporteField;
        
        private decimal ImporteEfectivoField;
        
        private string NtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PresupuestoField;
        
        private string PwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        private int TipoAfectacionField;
        
        private int TipoMovimientoField;
        
        private int TopField;
        
        private int TransaccionField;
        
        private string UrlField;
        
        private string UsrField;
        
        private string WsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((this.ConceptoField.Equals(value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Divisa {
            get {
                return this.DivisaField;
            }
            set {
                if ((this.DivisaField.Equals(value) != true)) {
                    this.DivisaField = value;
                    this.RaisePropertyChanged("Divisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ImporteEfectivo {
            get {
                return this.ImporteEfectivoField;
            }
            set {
                if ((this.ImporteEfectivoField.Equals(value) != true)) {
                    this.ImporteEfectivoField = value;
                    this.RaisePropertyChanged("ImporteEfectivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nt {
            get {
                return this.NtField;
            }
            set {
                if ((object.ReferenceEquals(this.NtField, value) != true)) {
                    this.NtField = value;
                    this.RaisePropertyChanged("Nt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((this.PedidoField.Equals(value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Presupuesto {
            get {
                return this.PresupuestoField;
            }
            set {
                if ((this.PresupuestoField.Equals(value) != true)) {
                    this.PresupuestoField = value;
                    this.RaisePropertyChanged("Presupuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Pwd {
            get {
                return this.PwdField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdField, value) != true)) {
                    this.PwdField = value;
                    this.RaisePropertyChanged("Pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoAfectacion {
            get {
                return this.TipoAfectacionField;
            }
            set {
                if ((this.TipoAfectacionField.Equals(value) != true)) {
                    this.TipoAfectacionField = value;
                    this.RaisePropertyChanged("TipoAfectacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoMovimiento {
            get {
                return this.TipoMovimientoField;
            }
            set {
                if ((this.TipoMovimientoField.Equals(value) != true)) {
                    this.TipoMovimientoField = value;
                    this.RaisePropertyChanged("TipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Transaccion {
            get {
                return this.TransaccionField;
            }
            set {
                if ((this.TransaccionField.Equals(value) != true)) {
                    this.TransaccionField = value;
                    this.RaisePropertyChanged("Transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usr {
            get {
                return this.UsrField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrField, value) != true)) {
                    this.UsrField = value;
                    this.RaisePropertyChanged("Usr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ws {
            get {
                return this.WsField;
            }
            set {
                if ((object.ReferenceEquals(this.WsField, value) != true)) {
                    this.WsField = value;
                    this.RaisePropertyChanged("Ws");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CAPAfectacionCajaService.ICajaService")]
    public interface ICajaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajaService/EnvioDatosServicioAfectacionCaja", ReplyAction="http://tempuri.org/ICajaService/EnvioDatosServicioAfectacionCajaResponse")]
        bool EnvioDatosServicioAfectacionCaja(CAPControlCaja.CAPAfectacionCajaService.ObjetoAfectacionCaja objetoAfectaCaja);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICajaServiceChannel : CAPControlCaja.CAPAfectacionCajaService.ICajaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CajaServiceClient : System.ServiceModel.ClientBase<CAPControlCaja.CAPAfectacionCajaService.ICajaService>, CAPControlCaja.CAPAfectacionCajaService.ICajaService {
        
        public CajaServiceClient() {
        }
        
        public CajaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CajaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnvioDatosServicioAfectacionCaja(CAPControlCaja.CAPAfectacionCajaService.ObjetoAfectacionCaja objetoAfectaCaja) {
            return base.Channel.EnvioDatosServicioAfectacionCaja(objetoAfectaCaja);
        }
    }
}
